const PersonalizeOutreachAutomationContent = () => {
    return (
        <div className="space-y-8">
            <h1 className="text-4xl font-bold mb-6">
                AI-Powered Lead Capture and Personalized Outreach Automation
            </h1>

            <div>
                <h2 className="text-2xl font-semibold mb-3">Project Overview</h2>
                <p className="leading-relaxed">
                    This n8n workflow completely automates the process of handling new consultation requests submitted via a landing page. Its primary goals are to instantly capture lead data, store it securely, generate a personalized, human-sounding introductory email using a specialized AI agent, and automatically send the welcome message to the prospect.
                </p>
                <p className="leading-relaxed mt-3">
                    This ensures an <strong>immediate and highly personalized</strong> first touchpoint, maximizing lead engagement and efficiency for the sales team. The workflow also utilizes <strong>PostgreSQL</strong> for both lead data storage and maintaining AI conversation memory for potential future interactions.
                </p>
            </div>

            <div>
                <h2 className="text-2xl font-semibold mb-3">System Architecture (Workflow Breakdown)</h2>

                <div className="mt-4">
                    <h3 className="text-xl font-semibold">Phase 1: Data Ingestion and Preparation</h3>
                    <ul className="list-disc list-inside space-y-2 mt-2 leading-relaxed">
                        <li>
                            <span className="font-medium text-white">Trigger (Webhook):</span> The workflow starts instantly when a contact form is submitted to the <strong>/upload-contact-information</strong> endpoint via a <strong>POST</strong> request. It uses header authentication for security.
                        </li>
                        <li>
                            <span className="font-medium text-white">Edit Fields (Set):</span> This node cleans and standardizes the incoming webhook data (e.g., `firstName`, `email`, `company`, `projectDesc`) by mapping them to internal variables. It also handles potential missing fields, such as setting an empty string for `website` if it's not provided.
                        </li>
                    </ul>
                </div>

                <div className="mt-6">
                    <h3 className="text-xl font-semibold">Phase 2: Database Storage and AI Personalization</h3>
                    <ul className="list-disc list-inside space-y-2 mt-2 leading-relaxed">
                        <li>
                            <span className="font-medium text-white">Insert rows in a table (Postgres):</span> The normalized lead information is immediately stored in the <strong>customer_consultation</strong> table in a PostgreSQL database with an initial `status` of <strong>"New"</strong>. This ensures no lead data is lost and creates a unique consultation ID.
                        </li>
                        <li>
                            <span className="font-medium text-white">AI Agent:</span> This is the core personalization engine, configured as a <strong>"Greeting Email Agent"</strong> from Talkvera.
                            <ul className="list-circle list-inside ml-5">
                                <li><strong>Goal:</strong> Draft exactly two concise, formal, and personalized opening paragraphs.</li>
                                <li><strong>LLM:</strong> Uses the <strong>OpenRouter Chat Model</strong> (`openai/gpt-5-mini`) for generation.</li>
                                <li><strong>Memory (Postgres Chat Memory):</strong> Connects to a separate PostgreSQL instance for conversation memory, using the prospect's `work_email` as the session key. This is a powerful feature for maintaining context for potential future interactions.</li>
                            </ul>
                        </li>
                    </ul>
                </div>

                <div className="mt-6">
                    <h3 className="text-xl font-semibold">Phase 3: Email Formatting and Final Delivery</h3>
                    <ul className="list-disc list-inside space-y-2 mt-2 leading-relaxed">
                        <li>
                            <span className="font-medium text-white">Code in JavaScript:</span> This crucial node takes the raw, personalized text generated by the AI Agent and wraps it within a complete, styled <strong>HTML email template</strong>. The resulting HTML body is assigned to a new variable: <strong>`htmlEmailBody`</strong>.
                        </li>
                        <li>
                            <span className="font-medium text-white">Send a message (Gmail):</span> The final email is sent to the prospect's `work_email` with a subject of <strong>"Welcome To Talkvera!"</strong> and the fully formatted <strong>`htmlEmailBody`</strong>.
                        </li>
                        <li>
                            <span className="font-medium text-white">Update rows in a table (Postgres):</span> The final step updates the corresponding row in the <strong>customer_consultation</strong> table, setting the `status` to <strong>"Send"</strong> and saving the entire <strong>`greetings_email_content`</strong> generated by the AI into the database.
                        </li>
                    </ul>
                </div>
            </div>


            <div>
                <h2 className="text-2xl font-semibold mb-3">Key Technologies and Configuration</h2>
                <p className="leading-relaxed">
                    This workflow relies on a tight integration between several specialized tools:
                </p>
                <ul className="list-disc list-inside space-y-2 mt-2 leading-relaxed">
                    <li><span className="font-medium text-white">AI Language Model:</span> OpenRouter (Model: `openai/gpt-5-mini`).</li>
                    <li><span className="font-medium text-white">Database:</span> PostgreSQL. Used for secure lead storage and as the backend for the AI's <strong>Chat Memory</strong>.</li>
                    <li><span className="font-medium text-white">Email Service:</span> Gmail. Handles the automated sending of the final HTML email.</li>
                    <li><span className="font-medium text-white">Custom Code:</span> The JavaScript <strong>Code</strong> node is essential for converting the plain AI text output into a deliverable, professional HTML email.</li>
                </ul>
            </div>
            

            <div>
                <h2 className="text-2xl font-semibold mb-3">Key Business Value</h2>
                <ul className="list-disc list-inside space-y-2 mt-2 leading-relaxed">
                    <li><span className="font-medium text-white">Instant Response:</span> Guarantees prospects receive a personalized response within seconds of submission, dramatically improving the lead experience.</li>
                    <li><span className="font-medium text-white">Personalization at Scale:</span> AI drafts unique greetings that acknowledge specific project needs, making the communication relevant without manual effort.</li>
                    <li><span className="font-medium text-white">Reliable Tracking:</span> Full end-to-end data logging in the database, including the final email content, ensures compliance and clear sales oversight.</li>
                </ul>
            </div>
        </div>
    );
};

export default PersonalizeOutreachAutomationContent;